In [1]:
import numpy as np
import pandas as pd

pd.set_option("display.max_rows", 20, "display.max_columns", 20)

In [2]:
# SH 逐笔委托

pd.read_parquet('Entrust/010107.parquet')

,SecurityID,TransactTime,OrderNo,Price,Balance,OrderBSFlag,OrdType,OrderIndex,ChannelNo,BizIndex
0,10107,20210104091501340,17081,101.15,15,B,A,44454,4,55346
1,10107,20210104091501770,24188,101.34,2,B,A,44455,4,55347
2,10107,20210104091502550,38094,101.50,2,S,A,44456,4,55348
3,10107,20210104091502550,38343,99.80,10,B,A,44457,4,55349
4,10107,20210104091503130,46061,103.00,2,S,A,44458,4,55350
...,...,...,...,...,...,...,...,...,...,...
477,10107,20210104145748880,7474561,101.39,50,S,A,7181718,4,11864194
478,10107,20210104145848700,6725021,101.16,96,B,D,7195450,4,11891793
479,10107,20210104145854210,7506394,101.39,56,S,A,7196720,4,11894013
480,10107,20210104145923580,7520327,100.58,5,B,A,7205059,4,11907958
481,10107,20210104145933040,299958,96.36,1,B,D,7207545,4,11912708

In [3]:
# SZ 逐笔委托

pd.read_parquet('order/000001.parquet')

,tradedate,OrigTime,SendTime,recvtime,dbtime,ChannelNo,MDStreamID,ApplSeqNum,SecurityID,SecurityIDSource,Price,OrderQty,TransactTime,Side,OrderType,ConfirmID,Contactor,ContactInfo,ExpirationDays,ExpirationType
0,20210104,20210104091500000,20210104091500252,20210104091500259,20210104091500263,2012,11,263,1,102,19.33,100,20210104091500000,2,2,0.0,NaN,NaN,0,0
1,20210104,20210104091500000,20210104091500252,20210104091500259,20210104091500263,2012,11,265,1,102,18.00,100,20210104091500000,1,2,0.0,NaN,NaN,0,0
2,20210104,20210104091500000,20210104091500277,20210104091500283,20210104091500284,2012,11,339,1,102,21.27,100,20210104091500000,2,2,0.0,NaN,NaN,0,0
3,20210104,20210104091500000,20210104091500297,20210104091500304,20210104091500308,2012,11,613,1,102,19.50,100,20210104091500000,2,2,0.0,NaN,NaN,0,0
4,20210104,20210104091500020,20210104091500315,20210104091500322,20210104091500329,2012,11,772,1,102,19.62,300,20210104091500020,2,2,0.0,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155622,20210104,20210104145959100,20210104145959109,20210104145959114,20210104145959115,2012,11,24940679,1,102,18.59,46900,20210104145959100,2,2,0.0,NaN,NaN,0,0
155623,20210104,20210104145959430,20210104145959436,20210104145959441,20210104145959442,2012,11,24940937,1,102,18.62,1200,20210104145959430,1,2,0.0,NaN,NaN,0,0
155624,20210104,20210104145959840,20210104145959854,20210104145959859,20210104145959859,2012,11,24941140,1,102,18.60,2500,20210104145959840,1,2,0.0,NaN,NaN,0,0
155625,20210104,20210104145959900,20210104145959915,20210104145959920,20210104145959921,2012,11,24941159,1,102,18.61,20000,20210104145959900,1,2,0.0,NaN,NaN,0,0
155626,20210104,20210104145959950,20210104145959962,20210104145959967,20210104145959967,2012,11,24941176,1,102,18.60,500,20210104145959950,1,2,0.0,NaN,NaN,0,0

In [4]:
# SH 逐笔成交

pd.read_parquet('Tick/010107.parquet')

,SecurityID,TradeTime,TradePrice,TradeQty,TradeAmount,BuyNo,SellNo,TradeIndex,ChannelNo,TradeBSFlag,BizIndex
0,10107,20210104092500480,101.22,2,2024.4,24188,138234,10893,4,N,55375
1,10107,20210104092500480,101.22,13,13158.6,157627,138234,10894,4,N,55376
2,10107,20210104092500480,101.22,15,15183.0,143269,138234,10895,4,N,55377
3,10107,20210104093353060,101.23,50,50615.0,350181,572753,266723,4,S,816503
4,10107,20210104093353060,101.23,500,506150.0,400060,572753,266724,4,S,816504
...,...,...,...,...,...,...,...,...,...,...,...
215,10107,20210104144354590,101.40,588,596232.0,7006739,6704294,4348423,4,B,11116759
216,10107,20210104144809700,101.39,90,91251.0,7136120,7038238,4442027,4,B,11329254
217,10107,20210104144809700,101.40,2002,2030028.0,7136120,6704294,4442028,4,B,11329255
218,10107,20210104144809700,101.40,5965,6048510.0,7136120,6902097,4442029,4,B,11329256
219,10107,20210104144814600,101.29,10,10129.0,6952280,7138788,4443530,4,S,11333364

In [5]:
# SZ 逐笔成交

pd.read_parquet('trade/000001.parquet')

,tradedate,OrigTime,SendTime,recvtime,dbtime,ChannelNo,MDStreamID,ApplSeqNum,SecurityID,SecurityIDSource,BidApplSeqNum,OfferApplSeqNum,Price,TradeQty,ExecType,tradetime
0,20210104,20210104091500030,20210104091500341,20210104091500347,20210104091500347,2012,11,1011,1,102,1010,0,0.0,100,4,20210104091500030
1,20210104,20210104091500030,20210104091500343,20210104091500349,20210104091500349,2012,11,1063,1,102,0,339,0.0,100,4,20210104091500030
2,20210104,20210104091500030,20210104091500422,20210104091500428,20210104091500429,2012,11,1864,1,102,1863,0,0.0,100,4,20210104091500030
3,20210104,20210104091502260,20210104091514886,20210104091514935,20210104091514935,2012,11,107517,1,102,0,18960,0.0,500,4,20210104091502260
4,20210104,20210104091511020,20210104091516697,20210104091517022,20210104091517023,2012,11,149596,1,102,147279,0,0.0,100,4,20210104091511020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141771,20210104,20210104150000000,20210104150000532,20210104150000545,20210104150000592,2012,11,24941999,1,102,24940148,24893482,18.6,100,F,20210104150000000
141772,20210104,20210104150000000,20210104150000532,20210104150000545,20210104150000592,2012,11,24942000,1,102,24940570,24893482,18.6,100,F,20210104150000000
141773,20210104,20210104150000000,20210104150000532,20210104150000545,20210104150000592,2012,11,24942001,1,102,24941140,24894150,18.6,100,F,20210104150000000
141774,20210104,20210104150000000,20210104150000532,20210104150000545,20210104150000592,2012,11,24942002,1,102,24941140,24895479,18.6,2400,F,20210104150000000
141775,20210104,20210104150000000,20210104150000532,20210104150000545,20210104150000592,2012,11,24942003,1,102,24941176,24895479,18.6,500,F,20210104150000000

In [6]:
# SH 行情快照全部

pd.read_parquet('Snapshot/010107.parquet')

,SecurityID,DateTime,PreClosePx,OpenPx,HighPx,LowPx,LastPx,TotalVolumeTrade,TotalValueTrade,InstrumentStatus,...,WithdrawBuyMoney,WithdrawSellNumber,WithdrawSellAmount,WithdrawSellMoney,ETFBuyNumber,ETFBuyAmount,ETFBuyMoney,ETFSellNumber,ETFSellAmount,ETFSellMoney
0,10107,20210104091507,101.3,0.00,0.00,0.00,0.00,0,0.0,OCALL,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
1,10107,20210104091610,101.3,0.00,0.00,0.00,0.00,0,0.0,OCALL,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
2,10107,20210104091755,101.3,0.00,0.00,0.00,0.00,0,0.0,OCALL,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
3,10107,20210104092337,101.3,0.00,0.00,0.00,0.00,0,0.0,OCALL,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
4,10107,20210104092404,101.3,0.00,0.00,0.00,0.00,0,0.0,OCALL,...,0.0,0,0,0.0,0,0,0.0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,10107,20210104145923,101.3,101.22,101.41,101.15,101.29,106415,107754474.6,TRADE,...,85514230.8,37,9266,9384780.5,0,0,0.0,0,0,0.0
529,10107,20210104145933,101.3,101.22,101.41,101.15,101.29,106415,107754474.6,TRADE,...,85515194.4,37,9266,9384780.5,0,0,0.0,0,0,0.0
530,10107,20210104150017,101.3,101.22,101.41,101.15,101.29,106415,107754474.6,CLOSE,...,85515194.4,37,9266,9384780.5,0,0,0.0,0,0,0.0
531,10107,20210104150027,101.3,101.22,101.41,101.15,101.40,106415,107754474.6,CLOSE,...,85515194.4,37,9266,9384780.5,0,0,0.0,0,0,0.0
532,10107,20210104150517,101.3,101.22,101.41,101.15,101.40,106415,107754474.6,ENDTR,...,85515194.4,37,9266,9384780.5,0,0,0.0,0,0,0.0

In [7]:
# SZ 行情快照档位

pd.read_parquet('level/000001.parquet')

,TradeDate,OrigTime,SendTime,RecvTime,DBTime,ChannelID,SecurityID,SecurityIDSource,MDStreamID,OfferPX1,...,OfferPX10,BidPX10,OfferSize10,BidSize10,NumOrders_B1,NoOrders_B1,OrderQty_B1,NumOrders_S1,NoOrders_S1,OrderQty_S1
0,20210104,20210104090009000,20210104090009561,20210104090010351,20210104090010355,1012,1,102,10,0.0,...,0.00,0.0,0,0,0,0,None,0,0,None
1,20210104,20210104090109000,20210104090109511,20210104090110193,20210104090110198,1012,1,102,10,0.0,...,0.00,0.0,0,0,0,0,None,0,0,None
2,20210104,20210104090209000,20210104090209516,20210104090210287,20210104090210307,1012,1,102,10,0.0,...,0.00,0.0,0,0,0,0,None,0,0,None
3,20210104,20210104090309000,20210104090309518,20210104090310309,20210104090310329,1012,1,102,10,0.0,...,0.00,0.0,0,0,0,0,None,0,0,None
4,20210104,20210104090409000,20210104090409512,20210104090410150,20210104090410152,1012,1,102,10,0.0,...,0.00,0.0,0,0,0,0,None,0,0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4909,20210104,20210104153003000,20210104153003618,20210104153003821,20210104153003834,1012,1,102,10,18.6,...,18.69,18.5,76300,969700,47,47,3400|5000|2000|800|100|500|2000|500|100|400|90...,62,50,11800|800|1000|16000|200|55400|500|2000|2600|4...
4910,20210104,20210104153103000,20210104153103620,20210104153103797,20210104153103801,1012,1,102,10,18.6,...,18.69,18.5,76300,969700,47,47,3400|5000|2000|800|100|500|2000|500|100|400|90...,62,50,11800|800|1000|16000|200|55400|500|2000|2600|4...
4911,20210104,20210104153203000,20210104153203624,20210104153203860,20210104153203915,1012,1,102,10,18.6,...,18.69,18.5,76300,969700,47,47,3400|5000|2000|800|100|500|2000|500|100|400|90...,62,50,11800|800|1000|16000|200|55400|500|2000|2600|4...
4912,20210104,20210104153303000,20210104153303619,20210104153304033,20210104153304095,1012,1,102,10,18.6,...,18.69,18.5,76300,969700,47,47,3400|5000|2000|800|100|500|2000|500|100|400|90...,62,50,11800|800|1000|16000|200|55400|500|2000|2600|4...
4913,20210104,20210104153403000,20210104153403620,20210104153403966,20210104153403969,1012,1,102,10,18.6,...,18.69,18.5,76300,969700,47,47,3400|5000|2000|800|100|500|2000|500|100|400|90...,62,50,11800|800|1000|16000|200|55400|500|2000|2600|4...

In [8]:
# SZ 行情快照

pd.read_parquet('hq_snap_spot/000001.parquet')

,TradeDate,OrigTime,SendTime,recvtime,dbtime,ChannelNo,SecurityID,SecurityIDSource,MDStreamID,PreClosePx,...,weightedavgbidpx,PreNAV,RealTimeNAV,WarrentPremiumRate,UpLimitPx,DownLimitPx,TotalLongPosition,c32,c33,c34
0,20210104,20210104090009000,20210104090009561,20210104090010351,20210104090010355,1012,1,102,10,19.34,...,0.00,0.0,0.0,0.0,21.27,17.41,0.0,0.0,0.0,0.0
1,20210104,20210104090109000,20210104090109511,20210104090110193,20210104090110198,1012,1,102,10,19.34,...,0.00,0.0,0.0,0.0,21.27,17.41,0.0,0.0,0.0,0.0
2,20210104,20210104090209000,20210104090209516,20210104090210287,20210104090210307,1012,1,102,10,19.34,...,0.00,0.0,0.0,0.0,21.27,17.41,0.0,0.0,0.0,0.0
3,20210104,20210104090309000,20210104090309518,20210104090310309,20210104090310329,1012,1,102,10,19.34,...,0.00,0.0,0.0,0.0,21.27,17.41,0.0,0.0,0.0,0.0
4,20210104,20210104090409000,20210104090409512,20210104090410150,20210104090410152,1012,1,102,10,19.34,...,0.00,0.0,0.0,0.0,21.27,17.41,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4909,20210104,20210104153003000,20210104153003618,20210104153003821,20210104153003834,1012,1,102,10,19.34,...,18.35,0.0,0.0,0.0,21.27,17.41,0.0,0.0,0.0,0.0
4910,20210104,20210104153103000,20210104153103620,20210104153103797,20210104153103801,1012,1,102,10,19.34,...,18.35,0.0,0.0,0.0,21.27,17.41,0.0,0.0,0.0,0.0
4911,20210104,20210104153203000,20210104153203624,20210104153203860,20210104153203915,1012,1,102,10,19.34,...,18.35,0.0,0.0,0.0,21.27,17.41,0.0,0.0,0.0,0.0
4912,20210104,20210104153303000,20210104153303619,20210104153304033,20210104153304095,1012,1,102,10,19.34,...,18.35,0.0,0.0,0.0,21.27,17.41,0.0,0.0,0.0,0.0
4913,20210104,20210104153403000,20210104153403620,20210104153403966,20210104153403969,1012,1,102,10,19.34,...,18.35,0.0,0.0,0.0,21.27,17.41,0.0,0.0,0.0,0.0